### ISSUE TITLE
Tidygraph URL in readme

### ISSUE THREAD

**Issue by mattkerlogue** [ukgovdatascience/orgsurveyr#29]
Minor bug. The URL for the references to `tidygraph` in `readme.md` and `readme.rmd` are missing an all important 'g' from 'tidygraph' - currently referring to https://github.com/thomasp85/tidyraph (which 404s), should be https://github.com/thomasp85/tidygraph.

**Comment by chapmandu2** [comment]
Thanks Matt good spot!

**Comment by chapmandu2** [comment]
Fixed in 9c7c189, part of #27
